-- Création des tables

DROP TABLE OFFRE CASCADE CONSTRAINTS;
DROP TABLE VENTE CASCADE CONSTRAINTS;
DROP TABLE SALLE_DE_VENTE CASCADE CONSTRAINTS;
DROP TABLE PRODUIT CASCADE CONSTRAINTS;
DROP TABLE CARACTERISTIQUES CASCADE CONSTRAINTS;
DROP TABLE CATEGORIE CASCADE CONSTRAINTS;
DROP TABLE UTILISATEUR CASCADE CONSTRAINTS;

CREATE TABLE UTILISATEUR
(
    EMAIL VARCHAR(255) PRIMARY KEY,
    NOM VARCHAR(255),
    PRENOM VARCHAR(255),
    ADRESSEPOSTALE VARCHAR(255)
);

CREATE TABLE CARACTERISTIQUES
(
    NOMCAR VARCHAR(255) PRIMARY KEY,
    VALEURCAR VARCHAR(255)
);

CREATE TABLE PRODUIT
(
    IDPRODUIT INT PRIMARY KEY,
    NOMPRODUIT VARCHAR(255),
    PRIXREVIENT INT CHECK (PRIXREVIENT > 0),
    STOCK INT,
    NOMCAR VARCHAR(255), 
    FOREIGN KEY (NOMCAR) REFERENCES CARACTERISTIQUES(NOMCAR)
);

CREATE TABLE CATEGORIE
(
    NOMCAT VARCHAR(255) PRIMARY KEY,
    DESCRCAT VARCHAR(255)
);

CREATE TABLE SALLE_DE_VENTE
(
    IDSALLE INT PRIMARY KEY,
    NOMCAT VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    FOREIGN KEY (NOMCAT) REFERENCES CATEGORIE(NOMCAT)
);

CREATE TABLE VENTE
(
    IDVENTE INT PRIMARY KEY,
    TYPEVENTE NUMBER(1), -- 1 pour ascendant, 0 pour descendant   
    PRIXDEPART INT CHECK (PRIXDEPART > 0),
    REVOCABLE NUMBER(1), -- 1 pour oui, 0 pour non
    LIMITEOFFRES INT CHECK (LIMITEOFFRES > 0),
    DUREE INT CHECK (DUREE > 0),
    IDPRODUIT INT NOT NULL,
    IDSALLE INT NOT NULL,
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT),
    FOREIGN KEY (IDSALLE) REFERENCES SALLE_DE_VENTE(IDSALLE)
);

CREATE TABLE OFFRE
(
    IDOFFRE INT PRIMARY KEY,
    EMAIL VARCHAR(255),
    IDVENTE INT,
    PRIXOFFRE INT CHECK (PRIXOFFRE > 0),
    DATEOFFRE DATE,
    HEUREOFFRE TIMESTAMP,
    QUANTITE INT CHECK (QUANTITE > 0),
    FOREIGN KEY (EMAIL) REFERENCES UTILISATEUR(EMAIL),
    FOREIGN KEY (IDVENTE) REFERENCES VENTE(IDVENTE)
);